import 'package:flutter/material.dart';
// import 'package:font_awesome_flutter/font_awesome_flutter.dart';

Color primarycolor = const Color(0xffE65100);
Color bgcolor = const Color(0xFFFFF5E0);

List<BoxShadow> shadow = [
  BoxShadow(color: Colors.grey.shade300, blurRadius: 30, offset: Offset(0, 10))
];
List<Map> firmname_detail = [
  {'name': "FRESSA", 'location': "Aligarh"},
];


List<Map> categories = [
  {'name': 'Juice', 'iconPath': 'img/e.png'},
  {'name': 'Beer', 'iconPath': 'img/aaa.png'},
  {'name': 'Drink', 'iconPath': 'img/ccc.png'},
  {'name': 'Softdrink', 'iconPath': 'img/d.png'},
  {'name': 'Shake', 'iconPath': 'img/b.png'},
  {'name': 'Alcohol', 'iconPath': 'img/c.png'},
];
List<Map> imagedata = [
  {'imagepath': 'img/a.png', 'name': 'drink1', 'price': '100'},
  {'imagepath': 'img/b.png', 'name': 'drink2', 'price': '100'},
  {'imagepath': 'img/c.png', 'name': 'drink3', 'price': '100'},
  {'imagepath': 'img/d.png', 'name': 'drink4', 'price': '100'},
  {'imagepath': 'img/e.png', 'name': 'drink5', 'price': '100'},
  {'imagepath': 'img/f.png', 'name': 'drink6', 'price': '100'},
  {'imagepath': 'img/g.png', 'name': 'drink7', 'price': '100'},
  {'imagepath': 'img/h.png', 'name': 'drink8', 'price': '100'},
  {'imagepath': 'img/i.png', 'name': 'drink9', 'price': '100'},
  {'imagepath': 'img/j.png', 'name': 'drink10', 'price': '100'},
  {'imagepath': 'img/k.png', 'name': 'drink11', 'price': '100'},
  {'imagepath': 'img/l.png', 'name': 'drink12', 'price': '100'},
  {'imagepath': 'img/m.png', 'name': 'drink13', 'price': '100'},
  {'imagepath': 'img/n.png', 'name': 'drink14', 'price': '100'},
  {'imagepath': 'img/o.png', 'name': 'drink15', 'price': '100'},
  {'imagepath': 'img/p.png', 'name': 'drink16', 'price': '100'},
  {'imagepath': 'img/q.png', 'name': 'drink17', 'price': '100'},
  {'imagepath': 'img/r.png', 'name': 'drink18', 'price': '100'},
  {'imagepath': 'img/s.png', 'name': 'drink19', 'price': '100'},
  {'imagepath': 'img/t.png', 'name': 'drink20', 'price': '100'},
  {'imagepath': 'img/u.png', 'name': 'drink21', 'price': '100'},
  {'imagepath': 'img/v.png', 'name': 'drink22', 'price': '100'},
  {'imagepath': 'img/w.png', 'name': 'drink23', 'price': '100'},
  {'imagepath': 'img/x.png', 'name': 'drink24', 'price': '100'},
  {'imagepath': 'img/y.png', 'name': 'drink25', 'price': '100'},
  {'imagepath': 'img/z.png', 'name': 'drink26', 'price': '100'},
  {'imagepath': 'img/aa.png', 'name': 'drink27', 'price': '100'},
  {'imagepath': 'img/bb.png', 'name': 'drink28', 'price': '100'},
  {'imagepath': 'img/cc.png', 'name': 'drink29', 'price': '100'},
  {'imagepath': 'img/dd.png', 'name': 'drink30', 'price': '100'},
  {'imagepath': 'img/ee.png', 'name': 'drink31', 'price': '100'},
  {'imagepath': 'img/ff.png', 'name': 'drink32', 'price': '100'},
  {'imagepath': 'img/gg.png', 'name': 'drink33', 'price': '100'},
  {'imagepath': 'img/hh.png', 'name': 'drink34', 'price': '100'},
  {'imagepath': 'img/ii.png', 'name': 'drink35', 'price': '100'},
  {'imagepath': 'img/jj.png', 'name': 'drink36', 'price': '100'},
  {'imagepath': 'img/kk.png', 'name': 'drink37', 'price': '100'},
  {'imagepath': 'img/ll.png', 'name': 'drink38', 'price': '100'},
  {'imagepath': 'img/mm.png', 'name': 'drink39', 'price': '100'},
  {'imagepath': 'img/nn.png', 'name': 'drink40', 'price': '100'},
  {'imagepath': 'img/oo.png', 'name': 'drink41', 'price': '100'},
  {'imagepath': 'img/pp.png', 'name': 'drink42', 'price': '100'},
  {'imagepath': 'img/qq.png', 'name': 'drink43', 'price': '100'},
  {'imagepath': 'img/rr.png', 'name': 'drink44', 'price': '100'},
  {'imagepath': 'img/ss.png', 'name': 'drink45', 'price': '100'},
  {'imagepath': 'img/tt.png', 'name': 'drink46', 'price': '100'},
  {'imagepath': 'img/uu.png', 'name': 'drink47', 'price': '100'},
  {'imagepath': 'img/vv.png', 'name': 'drink48', 'price': '100'},
  {'imagepath': 'img/ww.png', 'name': 'drink49', 'price': '100'},
  {'imagepath': 'img/xx.png', 'name': 'drink50', 'price': '100'},
  {'imagepath': 'img/yy.png', 'name': 'drink51', 'price': '100'},
  {'imagepath': 'img/zz.png', 'name': 'drink52', 'price': '100'},
  {'imagepath': 'img/aaa.png', 'name': 'drink53', 'price': '100'},
  {'imagepath': 'img/bbb.png', 'name': 'drink54', 'price': '100'},
  {'imagepath': 'img/ccc.png', 'name': 'drink55', 'price': '100'},
  {'imagepath': 'img/ddd.png', 'name': 'drink56', 'price': '100'},
  {'imagepath': 'img/eee.png', 'name': 'drink57', 'price': '100'},
  {'imagepath': 'img/fff.png', 'name': 'drink58', 'price': '100'},
  {'imagepath': 'img/ggg.png', 'name': 'drink59', 'price': '100'},
  {'imagepath': 'img/hhh.png', 'name': 'drink60', 'price': '100'},
  {'imagepath': 'img/iii.png', 'name': 'drink61', 'price': '100'},
  {'imagepath': 'img/jjj.png', 'name': 'drink62', 'price': '100'},
  {'imagepath': 'img/kkk.png', 'name': 'drink63', 'price': '100'},
  {'imagepath': 'img/lll.png', 'name': 'drink64', 'price': '100'},
  {'imagepath': 'img/mmm.png', 'name': 'drink65', 'price': '100'},
  {'imagepath': 'img/nmn.png', 'name': 'drink66', 'price': '100'},
  {'imagepath': 'img/ooo.png', 'name': 'drink67', 'price': '100'},
  {'imagepath': 'img/ppp.png', 'name': 'drink68', 'price': '100'},
  {'imagepath': 'img/qqq.png', 'name': 'drink69', 'price': '100'},
  {'profile': 'img/profile.png'},
];
